notes/urls.py
from django.urls import path
from notes.views import *

urlpatterns = [
    path("", main_page_view, name="main"),
    path("back/", return_back_view, name="back"),
    path("<int:id>/", profile_view, name="profile"),
    path("notes/<int:id>/", note_view, name="note"),
    path('notes/<int:id>/delete/', delete_note_view, name="delete_note"),
    path('notes/comments/<int:id>/delete/', delete_comment_view, name="delete_comment"),
    path("settings/", settings_view, name="settings"),
    path("messages/", rooms_messages_view, name="messages_rooms"),
    path("messages/<int:id>/", room_messages_view, name="messages_room"),
    path('messages/message/<int:id>/delete/', delete_message_view, name="delete_message"),
    path("registration/", registration_view, name="registration"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.files.uploadhandler import InMemoryUploadedFile
from PIL import Image
import io


class Note(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    profile = models.ForeignKey("Profile", on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    private = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text[0:50]

    class Meta:
        ordering = ['-updated_at']


class Like(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    note = models.ForeignKey("Note", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} like {self.note}"


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='uploads/avatars/', default="uploads/avatars/user.png", blank=True, null=True)
    about = models.TextField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def save(self):
        if self.avatar.height > 300 or self.avatar.width > 300:
            img = Image.open(io.BytesIO(self.avatar.read()))
            if img.mode != 'RGB':
                img = img.convert('RGB')
            img.thumbnail((300,300), Image.ANTIALIAS)
            output = io.BytesIO()
            img.save(output, format='JPEG')
            output.seek(0)
            self.avatar = InMemoryUploadedFile (output,'ImageField', "%s.jpg" %self.avatar.name.split('.')[0], 'image/jpeg',"Content-Type: charset=utf-8", None)
        super(Profile, self).save()


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey("Profile", on_delete=models.CASCADE, blank=True, null=True)
    note = models.ForeignKey("Note", on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text[0:50]

    class Meta:
        ordering = ['-created_at']


class Room(models.Model):
    profiles = models.ManyToManyField("Profile", blank=True, null=True)

    def __str__(self):
        return str(self.id)


class Message(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey("Profile", on_delete=models.CASCADE, blank=True, null=True)
    room = models.ForeignKey("Room", on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text[0:50]

    class Meta:
        ordering = ['-created_at']

notes/forms.py
from django import forms
from .models import Message, Note, Profile, Comment, Message
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class NotesForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text', 'private']

class UserForm(UserCreationForm):
    username = forms.CharField(min_length=8, max_length=150, help_text="")
    email = forms.EmailField(max_length=254, help_text="", required=True)
    password1 = forms.CharField(label="Password", help_text="", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password", help_text="", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2' ]

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =  ['about', 'avatar']

    def clean_avatar(self):
        if self.changed_data == ['avatar']:
            avatar = self.cleaned_data.get('avatar', False)
            if avatar:
                if avatar.size > 1100000:
                    raise ValidationError("Please upload a picture smaller than 1 MB")
                return avatar

class CommentForm(forms.ModelForm):
    text = forms.CharField(min_length=3)
    class Meta:
        model = Comment
        fields = ['text']

class MessageForm(forms.ModelForm):
    text = forms.CharField(min_length=3)
    class Meta:
        model = Message
        fields = ['text']

notes/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Like, Note, Profile, Comment, Message, Room
from .forms import NotesForm, UserForm, UserProfileForm, CommentForm, MessageForm


@login_required
def return_back_view(request):
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def rooms_messages_view(request):
    context = {}
    # Logged user
    request_user_profile = Profile.objects.get(user=request.user)
    context['request_user'] = request.user
    context['request_user_profile'] = request_user_profile
    # Rooms + delete room
    rooms = Room.objects.filter(profiles__user=request.user)
    for room in rooms:
        if request.POST.get('delete_room' + str(room.id)):
            obj = Room.objects.get(id=room.id)
            obj.delete()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    context['rooms'] = rooms
    return render(request, 'notes/messages.html', context)


@login_required
def room_messages_view(request, id):
    context = {}
    # Logged user
    request_user_profile = Profile.objects.get(user=request.user)
    context['request_user'] = request.user
    context['request_user_profile'] = request_user_profile
    # Rooms + delete room
    rooms = Room.objects.filter(profiles__user=request.user)
    for room in rooms:
        if request.POST.get('delete_room' + str(room.id)):
            obj = Room.objects.get(id=room.id)
            obj.delete()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    context['rooms'] = rooms
    # Room
    room = Room.objects.get(id=id, profiles__user=request.user)
    messages = Message.objects.filter(room=room)
    context['messages'] = messages
    context['room_selected'] = room
    # Create messages
    message_form = MessageForm()
    if request.POST.get('send_message'):
        message_form = MessageForm(request.POST)
        if message_form.is_valid():
            message_form = message_form.save(commit=False)
            message_form.user = request.user
            message_form.profile = request_user_profile
            message_form.room = room
            message_form.save()
            return redirect(reverse("messages_room", kwargs={"id": id}))
    context['message_form'] = message_form
    for message in messages:
        # Edit massages
        if request.POST.get('edit_message' + str(message.id)):
            message1 = Message.objects.get(id=message.id, user=request.user)
            message_form = MessageForm(instance=message1)
            context['message_form_edit'] = message_form
            context['message1'] = message1
        if request.POST.get('save_edit_message' + str(message.id)):
            message1 = Message.objects.get(id=message.id, user=request.user)
            message_form = MessageForm(request.POST, instance=message1)
            if message_form.is_valid():
                message_form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            context['message_form_edit'] = message_form
            context['message1'] = message1
    return render(request, 'notes/messages.html', context)


@login_required
def profile_view(request, id):
    context = {}
    # Load profile notes
    if id == request.user.id:
        queryset = Note.objects.filter(user=id)
    else:
        queryset = Note.objects.filter(user=id, private=False)
    context['object_list'] = queryset
    # Profile
    user_main = User.objects.get(id=id)
    profile_main = Profile.objects.get(user=user_main)
    context['user_main'] = user_main
    context['profile_main'] = profile_main
    # Logged user
    request_user_profile = Profile.objects.get(user=request.user)
    context['request_user'] = request.user
    context['request_user_profile'] = request_user_profile
    # Create notes
    if request.POST.get('new'):
        new_form = NotesForm()
        context['form'] = new_form
    if request.POST.get('save'):
        new_form = NotesForm(request.POST)
        if new_form.is_valid():
            nf = new_form.save(commit=False)
            nf.user = request.user
            nf.profile = request_user_profile
            nf.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        context['form'] = new_form
    # Send message to user, create room or redirect
    if request.POST.get('send_message_to'):
        uniq_room_id = int(f"{request_user_profile.user.id}{profile_main.user.id}")
        try:
            room = Room.objects.create(id=uniq_room_id)
            room.profiles.add(request_user_profile, profile_main)
        except:None
        return redirect(reverse("messages_room", kwargs={"id": uniq_room_id}))
    return render(request, 'notes/profile.html', context)


@login_required
def main_page_view(request):
    context = {}
    # Load notes + search users, notes
    search_str = request.GET.get("search", False)
    if search_str:
        queryset1 = Note.objects.filter(user=request.user.id, text__contains=search_str)
        queryset2 = Note.objects.filter(private=False, text__contains=search_str)
        queryset = queryset1 | queryset2
        try:
            queryset_people = User.objects.filter(username__contains=search_str)
            context['people_list'] = queryset_people
        except:None
    else:
        queryset = Note.objects.filter(private=False)
    context['object_list'] = queryset
    # Logged user
    context['request_user'] = request.user
    context['request_user_profile'] = Profile.objects.get(user=request.user)
    return render(request, 'notes/home.html', context)


@login_required
def note_view(request, id):
    context = {}
    obj = Note.objects.get(id=id)
    context['object'] = obj
    # Logged user
    request_user_profile = Profile.objects.get(user=request.user)
    context['request_user'] = request.user
    context['request_user_profile'] = request_user_profile
    # Likes
    if request.POST.get('like' + str(obj.id)):
        try:
            uniq_like_id = int(f"{request.user.id}{obj.id}")
            Like.objects.create(user=request.user, note=obj, id=uniq_like_id)
        except:None
    # Edit notes
    if request.POST.get('edit' + str(obj.id)):
        obj_edit = Note.objects.get(id=obj.id, user=request.user.id)
        edit_form = NotesForm(instance=obj_edit)
        context['form'] = edit_form
        context['object1'] = obj_edit
    if request.POST.get('save' + str(obj.id)):
        obj_edit = Note.objects.get(id=obj.id, user=request.user.id)
        edit_form = NotesForm(request.POST, instance=obj_edit)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        context['form'] = edit_form
        context['object1'] = obj_edit 
    # Comments
    comment_form = CommentForm()
    context['comment_form'] = comment_form
    context['comment_obj'] = obj
    if request.POST.get('save_comment' + str(obj.id)):
        comment_obj = Note.objects.get(id=obj.id)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.user = request.user
            comment_form.profile = request_user_profile
            comment_form.note = obj
            comment_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        context['comment_form'] = comment_form
        context['comment_obj'] = comment_obj
    comments = Comment.objects.filter(note=obj)
    for comment in comments:
        # Edit comments
        if request.POST.get('edit_comment' + str(comment.id)):
            comment1 = Comment.objects.get(id=comment.id, user=request.user)
            comment_form = CommentForm(instance=comment1)
            context['comment_form_edit'] = comment_form
            context['comment1'] = comment1
        if request.POST.get('save_edit_comment' + str(comment.id)):
            comment1 = Comment.objects.get(id=comment.id, user=request.user)
            comment_form = CommentForm(request.POST, instance=comment1)
            if comment_form.is_valid():
                comment_form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            context['comment_form_edit'] = comment_form
            context['comment1'] = comment1
    return render(request, 'notes/detail.html', context)


@login_required
def delete_note_view(request, id):
    obj = get_object_or_404(Note, id=id, user=request.user)
    obj.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_comment_view(request, id):
    obj = get_object_or_404(Comment, id=id)
    if obj.user == request.user or obj.note.user == request.user:
        obj.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_message_view(request, id):
    obj = get_object_or_404(Message, id=id)
    if obj.user == request.user:
        obj.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def settings_view(request):
    context = {}
    profile = Profile.objects.get(user=request.user)
    update_user_form = UserForm(request.POST or None, instance=request.user)
    #update_user_form = PasswordChangeForm(user=request.user, data=request.POST or None)
    update_profile_user_form = UserProfileForm(request.POST or None, request.FILES or None, instance=profile)
    if request.POST.get('update_account'):
        if update_user_form.is_valid() and update_profile_user_form.is_valid():
            if update_profile_user_form.changed_data == ['avatar']:

templates/notes/comment.html
{% load humanize %}

<div class="shadow ms-3 m-1 rounded border border-secondary" style="background-color:#e9ecef">
    <div class="input-group">
        <input type="text" name="text" placeholder="Add comment" class="form-control">
        <input class="btn btn-outline-primary btn-sm" type="submit" value="OK" name="save_comment{{comment_obj.id}}">
    </div>
</div>

{% for comment in object.comment_set.all %}
<div class="shadow ms-3 m-1 rounded border border-secondary" style="background-color:#e9ecef">
    <div class="row p-1">
        <div class="col-auto me-auto">
            <small><a class="link-dark" style="text-decoration:none" aria-current="page" href="{% url 'profile' comment.profile.user.id %}">
            <img class="border border-secondary rounded" src="{% if comment.profile.avatar %}{{ comment.profile.avatar.url }}{% else %}/media/uploads/avatars/user.png{% endif %}" width="20" height="20">
            <b>{{ comment.profile.user }}</b></a></small>
            <small title="Created: {{ comment.created_at|naturaltime }}">Updated: {{ comment.updated_at|naturaltime }}</small>
        </div>
        <div class="col-auto">
            <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <b>≡</b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if comment.profile.user == request.user %}
                <li><input title="Edit comment" class="dropdown-item" type="submit" value="✎ edit" name="edit_comment{{ comment.id }}"></li>
                {% else %}
                <li><a class="dropdown-item" aria-current="page" href="#">🏴 report</a></li>
                {% endif %}
                {% if object.profile.user == request.user or comment.profile.user == request.user %}
                <li><a title="Delete comment" class="dropdown-item" aria-current="page" href="{% url 'delete_comment' comment.id %}">✘ delete</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="p-0">
        {% if comment.text|length <= 100 %}
        <textarea class="form-control" id="floatingTextarea2" rows="1" style="border:0" readonly>{{ comment.text }}</textarea>
        {% elif comment.text|length <= 300 %}
        <textarea class="form-control" id="floatingTextarea2" rows="3" style="border:0" readonly>{{ comment.text }}</textarea>
        {% elif comment.text|length <= 600 %}
        <textarea class="form-control" id="floatingTextarea2" rows="6" style="border:0" readonly>{{ comment.text }}</textarea>
        {% elif comment.text|length <= 900 %}
        <textarea class="form-control" id="floatingTextarea2" rows="8" style="border:0" readonly>{{ comment.text }}</textarea>
        {% else %}
        <textarea class="form-control" id="floatingTextarea2" rows="10" style="border:0" readonly>{{ comment.text }}</textarea>
        {% endif %}
    </div>
</div>
{% endfor %}

templates/notes/create-update.html
<style>
    .overlay {
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0,0,0,0.5);
        z-index: 2;
        cursor: pointer;
    }
</style>
<div class="overlay">
    <div class="modal" tabindex="-1" style="display:initial">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        {% if comment1 %}
                        Edit comment
                        {% elif object1 %}
                        Edit note
                        {% elif message1 %}
                        Edit message
                        {% else %}
                        Create note
                        {% endif %}
                    </h5>
                    <a class="btn-close" role="button" aria-label="Close" href="{% url 'back' %}"></a>
                </div>
                <form method="POST" class="m-3 mt-5" autocomplete="off">{% csrf_token %}
                    {% if comment1 %}
                    <input type="text" name="text" class="form-control mb-3" value="{{comment1.text}}">
                    <div class="col-10">
                        <input class="btn btn-light btn-sm" type="submit" value="Save" name="save_edit_comment{{ comment1.id }}">
                        <a class="btn btn-light btn-sm" href="{% url 'back' %}">Cancel</a>
                    </div>
                    {% elif message1 %}
                    <input type="text" name="text" class="form-control mb-3" value="{{message1.text}}">
                    <div class="col-10">
                        <input class="btn btn-light btn-sm" type="submit" value="Save" name="save_edit_message{{ message1.id }}">
                        <a class="btn btn-light btn-sm" href="{% url 'back' %}">Cancel</a>
                    </div>
                    {% else %}
                    <textarea name="text" class="form-control mb-3" id="exampleFormControlTextarea1" rows="10">{% if object1.text %}{{object1.text}}{% endif %}</textarea>
                    <div class="row">
                        <div class="col-auto">
                            <input class="btn btn-light btn-sm" type="submit" value="Save" {% if object1 %}name="save{{ object1.id }}"{% else %}name="save"{% endif %}>
                            <a class="btn btn-light btn-sm" href="{% url 'back' %}">Cancel</a>
                        </div>
                        <div class="col-auto m-1 form-check">
                            <input class="form-check-input" type="checkbox" id="defaultCheck1" name="private"{% if object1.private == True %} checked{% endif %}>
                            <label class="form-check-label" for="defaultCheck1">Private</label>
                        </div>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

templates/notes/create.html
{% extends "notes/list.html" %}

{% block title %}Details{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

templates/notes/detail.html
{% extends "base.html" %}

{% block title %}Note{% endblock %}

{% block content %}

<form method="POST" class="m-3" autocomplete="off">{% csrf_token %}
    <div class="w-100">
        {% include "notes/note.html" %}
        {% include "notes/comment.html" %}
    </div>
</form>
{% if form %}{% include "notes/create-update.html" %}{% endif %}
{% if comment1 %}{% include "notes/create-update.html" %}{% endif %}

{% endblock %}

templates/notes/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="m-2">
  {% for object in object_list %}
  <form method="POST" class="row row-cols-auto m-1" style="margin:0" action="{% url 'note' object.id %}">{% csrf_token %}
    <div class="container p-1 w-100">
      {% include "notes/note.html" %}
      <!--{% include "notes/comment.html" %}-->
    </div>
  </form>
  {% endfor %}

  {% if people_list %}
  {% for object in people_list %}
  <a class="nav-link m-2" aria-current="page" href="{% url 'profile' object.id %}">
    {% if object.profile.avatar %}<img src="{{ object.profile.avatar.url }}" width="35" height="35">{% else %}<img src="/media/uploads/user.png" width="35" height="35">{% endif %}
    @{{ object }}
  </a>
</div>
{% endfor %}
{% endif %}

{% if form %}{% include "notes/create-update.html" %}{% endif %}
{% if comment_form %}{% include "notes/create-update.html" %}{% endif %}

{% endblock %}

templates/notes/note.html
{% load humanize %}
<div class="shadow m-1 rounded border border-secondary" style="background-color:#e9ecef">
    <div class="row p-1">
        <div class="col-auto me-auto">
            <small><a class="link-dark" style="text-decoration:none" aria-current="page" href="{% url 'profile' object.profile.user.id %}">
            <img class="border border-secondary rounded" src="{% if object.profile.avatar %}{{ object.profile.avatar.url }}{% else %}/media/uploads/avatars/user.png{% endif %}" width="20" height="20">
            <b>{{ object.profile.user }}</b></a></small>
            <small title="Created: {{ object.created_at|naturaltime }}">Updated: {{ object.updated_at|naturaltime }}</small>
        </div>
        <div class="col-auto dropdown">
            <a class="nav-link p-0" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <b>≡</b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if object.profile.user == request.user %}
                <li><input class="dropdown-item" type="submit" value="✎ edit" name="edit{{ object.id }}"></li>
                <li><a class="dropdown-item" aria-current="page" href="{% url 'delete_note' object.id %}">✘ delete</a></li>
                {% else %}
                <li><a class="dropdown-item" aria-current="page" href="#">🏴 report</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="p-0">
        {% if object.text|length <= 300 %}
        <textarea class="form-control" id="floatingTextarea2" rows="3" style="border:0" readonly>{{ object.text }}</textarea>
        {% elif object.text|length <= 600 %}
        <textarea class="form-control" id="floatingTextarea2" rows="6" style="border:0" readonly>{{ object.text }}</textarea>
        {% elif object.text|length <= 900 %}
        <textarea class="form-control" id="floatingTextarea2" rows="8" style="border:0" readonly>{{ object.text }}</textarea>
        {% else %}
        <textarea class="form-control" id="floatingTextarea2" rows="10" style="border:0" readonly>{{ object.text }}</textarea>
        {% endif %}
    </div>
    <div class="row px-1 pb-1 m-0">
        <div class="col-auto me-auto">
            <input title="Like note" class="btn btn-outline-primary p-0" style="border:0" type="submit" value="👍" name="like{{ object.id }}">
            <a class="btn btn-outline-primary p-0" style="border:0" style="text-decoration:none;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ object.like_set.all|length }}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for like in object.like_set.all %}
                <li><small class="dropdown-item"><a class="link-dark" style="text-decoration:none" aria-current="page" href="{% url 'profile' like.user.id %}">
                <img src="{% if like.user.profile.avatar %}{{ like.user.profile.avatar.url }}{% else %}/media/uploads/avatars/user.png{% endif %}" width="20" height="20">
                {{ like.user }}</a></small></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-auto">
            {% url 'profile' request.user.id as profile_request_url %}{% url 'note' object.id as obj_profile_url %}
            {% if request.get_full_path == profile_request_url or request.get_full_path == obj_profile_url %}
            {% if object.private == True %}Private{% else %}Public{% endif %}
            {% endif %}
            <a title="See comments" class="btn btn-outline-primary p-0" style="border:0" aria-current="page" href="{% url 'note' object.id %}">💬 {{ object.comment_set.all|length }}</a>
        </div>
    </div>
</div>

templates/notes/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="row m-2">
  <div class="col-auto p-0 card border-bottom border-end border-secondary" style="background-color:#e9ecef">
    {% if user.is_authenticated and profile_main %}
    <img class="border-bottom border-secondary rounded" src="{% if profile_main.avatar %}{{ profile_main.avatar.url }}{% else %}/media/uploads/avatars/user.png{% endif %}" style="background-color:#e9ecef">
    <div class="card-body" style="max-width:250px">
      <h5 class="card-title">@{{ user_main.username }}</h5>
      <p class="card-text">{% if user_main.first_name %}({{ user_main.first_name }} {{ user_main.last_name }}){% endif %}</p>
      <p class="card-text">{% if profile_main.about %}{{ profile_main.about }}{% endif %}</p>
    </div>
    {% if profile_main.user != request.user %}
    <form method="POST" style="margin:0">{% csrf_token %}
      <div class="card-body">
        <input class="card-link" type="submit" value="Send message" name="send_message_to">
      </div>
    </form>
    {% endif %}
    {% endif %}
  </div>
  <div class="col ps-0">
    {% for object in object_list %}
    <form method="POST" style="margin:0" action="{% url 'note' object.id %}">{% csrf_token %}
      <div class="row row-cols-auto m-1">
        <div class="container m-1 p-1 w-100">
          {% include "notes/note.html" %}
          <!--{% include "notes/comment.html" %}-->
        </div>
      </div>
    </form>
    {% endfor %}
  </div>
</div>
{% if form %}{% include "notes/create-update.html" %}{% endif %}
{% if comment_form %}{% include "notes/create-update.html" %}{% endif %}

{% endblock %}

templates/notes/settings.html
{% extends "base.html" %}

{% block title %}Notes - Settings{% endblock %}

{% block content %}
<form method="post" class="m-4" enctype="multipart/form-data">{% csrf_token %}
  <div class="m-1">
    <p><b>You profile</b></p>
    {% load crispy_forms_tags %}
    {{ update_user_form|crispy }}
    {{ update_profile_user_form|crispy }}
    <br>
    <input class="btn btn-warning btn-sm" type="submit" value="Update" name="update_account">
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'profile' request.user.id %}">To notes</a>
  </div>
</form>

{% endblock %}